/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Helper config to allow switching off Supabase functions and use local API paths
export const USE_SUPABASE = false;

// When running without Supabase functions, use relative local endpoints prefixed with the function namespace.
export function fn(path: string) {
	// trim leading slash
	const clean = path.replace(/^\/+/, '');
	return `/make-server-b35a818f/${clean}`;
}

// Legacy exports kept for compatibility; not used when USE_SUPABASE is false.
export const projectId = "";
export const publicAnonKey = "";