/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// KV helper that works with either Supabase (Deno) or Cloudflare Workers KV.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const supabaseClient = () => createClient(
  Deno.env.get("SUPABASE_URL"),
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
);

const hasWorkerKV = typeof globalThis !== 'undefined' && (globalThis as any).KV_STORE;

// Set stores a key-value pair in the platform KV.
export const set = async (key: string, value: any): Promise<void> => {
  if (hasWorkerKV) {
    const kv = (globalThis as any).KV_STORE;
    await kv.put(key, JSON.stringify(value));
    return;
  }

  const supabase = supabaseClient();
  const { error } = await supabase.from("kv_store_b35a818f").upsert({ key, value });
  if (error) throw new Error(error.message);
};

// Get retrieves a key-value pair from the platform KV.
export const get = async (key: string): Promise<any> => {
  if (hasWorkerKV) {
    const kv = (globalThis as any).KV_STORE;
    const raw = await kv.get(key);
    if (raw === null) return null;
    try { return JSON.parse(raw); } catch { return raw; }
  }

  const supabase = supabaseClient();
  const { data, error } = await supabase.from("kv_store_b35a818f").select("value").eq("key", key).maybeSingle();
  if (error) throw new Error(error.message);
  return data?.value ?? null;
};

// Delete deletes a key-value pair from the platform KV.
export const del = async (key: string): Promise<void> => {
  if (hasWorkerKV) {
    const kv = (globalThis as any).KV_STORE;
    await kv.delete(key);
    return;
  }

  const supabase = supabaseClient();
  const { error } = await supabase.from("kv_store_b35a818f").delete().eq("key", key);
  if (error) throw new Error(error.message);
};

// Sets multiple key-value pairs in the platform KV.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  if (hasWorkerKV) {
    const kv = (globalThis as any).KV_STORE;
    await Promise.all(keys.map((k, i) => kv.put(k, JSON.stringify(values[i]))));
    return;
  }

  const supabase = supabaseClient();
  const { error } = await supabase.from("kv_store_b35a818f").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) throw new Error(error.message);
};

// Gets multiple key-value pairs from the platform KV.
export const mget = async (keys: string[]): Promise<any[]> => {
  if (hasWorkerKV) {
    const kv = (globalThis as any).KV_STORE;
    const results = await Promise.all(keys.map(async (k) => {
      const v = await kv.get(k);
      if (v === null) return null;
      try { return JSON.parse(v); } catch { return v; }
    }));
    return results;
  }

  const supabase = supabaseClient();
  const { data, error } = await supabase.from("kv_store_b35a818f").select("value").in("key", keys);
  if (error) throw new Error(error.message);
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the platform KV.
export const mdel = async (keys: string[]): Promise<void> => {
  if (hasWorkerKV) {
    const kv = (globalThis as any).KV_STORE;
    await Promise.all(keys.map((k) => kv.delete(k)));
    return;
  }

  const supabase = supabaseClient();
  const { error } = await supabase.from("kv_store_b35a818f").delete().in("key", keys);
  if (error) throw new Error(error.message);
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  if (hasWorkerKV) {
    const kv = (globalThis as any).KV_STORE;
    const list = await kv.list({ prefix, limit: 1000 });
    const values = await Promise.all(list.keys.map(async (entry: any) => {
      const v = await kv.get(entry.name);
      try { return JSON.parse(v); } catch { return v; }
    }));
    return values;
  }

  const supabase = supabaseClient();
  const { data, error } = await supabase.from("kv_store_b35a818f").select("key, value").like("key", prefix + "%");
  if (error) throw new Error(error.message);
  return data?.map((d) => d.value) ?? [];
};